package com.probridge.vbox.dao;

import com.probridge.vbox.model.Course;
import com.probridge.vbox.model.CourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int countByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByPrimaryKey(String courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    List<Course> selectByExample(CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    Course selectByPrimaryKey(String courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") Course record, @Param("example") CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExample(@Param("record") Course record, @Param("example") CourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_list
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKey(Course record);
}