package com.probridge.vbox.dao;

import com.probridge.vbox.model.GMImage;
import com.probridge.vbox.model.GMImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GMImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int countByExample(GMImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByExample(GMImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByPrimaryKey(Integer gmImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insert(GMImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insertSelective(GMImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    List<GMImage> selectByExample(GMImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    GMImage selectByPrimaryKey(Integer gmImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") GMImage record, @Param("example") GMImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExample(@Param("record") GMImage record, @Param("example") GMImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKeySelective(GMImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKey(GMImage record);
}