package com.probridge.vbox.dao;

import com.probridge.vbox.model.PreApprovedUser;
import com.probridge.vbox.model.PreApprovedUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreApprovedUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int countByExample(PreApprovedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByExample(PreApprovedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByPrimaryKey(String preapproveUserName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insert(PreApprovedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insertSelective(PreApprovedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    List<PreApprovedUser> selectByExample(PreApprovedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    PreApprovedUser selectByPrimaryKey(String preapproveUserName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") PreApprovedUser record, @Param("example") PreApprovedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExample(@Param("record") PreApprovedUser record, @Param("example") PreApprovedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKeySelective(PreApprovedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKey(PreApprovedUser record);
}