package com.probridge.vbox.dao;

import com.probridge.vbox.model.SysParam;
import com.probridge.vbox.model.SysParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int countByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByPrimaryKey(String sysparamKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insert(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insertSelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    List<SysParam> selectByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    SysParam selectByPrimaryKey(String sysparamKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExample(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKeySelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKey(SysParam record);
}