package com.probridge.vbox.dao;

import com.probridge.vbox.model.WordOfTheDay;
import com.probridge.vbox.model.WordOfTheDayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordOfTheDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int countByExample(WordOfTheDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByExample(WordOfTheDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int deleteByPrimaryKey(Integer wofdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insert(WordOfTheDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int insertSelective(WordOfTheDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    List<WordOfTheDay> selectByExample(WordOfTheDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    WordOfTheDay selectByPrimaryKey(Integer wofdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") WordOfTheDay record, @Param("example") WordOfTheDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByExample(@Param("record") WordOfTheDay record, @Param("example") WordOfTheDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKeySelective(WordOfTheDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    int updateByPrimaryKey(WordOfTheDay record);
}