package com.probridge.vbox.model;

import java.io.Serializable;
import java.util.Date;

public class GMImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_master_images.gm_image_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer gmImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_master_images.gm_image_filename
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String gmImageFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_master_images.gm_image_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String gmImageDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_master_images.gm_image_lock
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String gmImageLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column golden_master_images.gm_image_creation_date
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Date gmImageCreationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table golden_master_images
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_master_images.gm_image_id
     *
     * @return the value of golden_master_images.gm_image_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getGmImageId() {
        return gmImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_master_images.gm_image_id
     *
     * @param gmImageId the value for golden_master_images.gm_image_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setGmImageId(Integer gmImageId) {
        this.gmImageId = gmImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_master_images.gm_image_filename
     *
     * @return the value of golden_master_images.gm_image_filename
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getGmImageFilename() {
        return gmImageFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_master_images.gm_image_filename
     *
     * @param gmImageFilename the value for golden_master_images.gm_image_filename
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setGmImageFilename(String gmImageFilename) {
        this.gmImageFilename = gmImageFilename == null ? null : gmImageFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_master_images.gm_image_description
     *
     * @return the value of golden_master_images.gm_image_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getGmImageDescription() {
        return gmImageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_master_images.gm_image_description
     *
     * @param gmImageDescription the value for golden_master_images.gm_image_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setGmImageDescription(String gmImageDescription) {
        this.gmImageDescription = gmImageDescription == null ? null : gmImageDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_master_images.gm_image_lock
     *
     * @return the value of golden_master_images.gm_image_lock
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getGmImageLock() {
        return gmImageLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_master_images.gm_image_lock
     *
     * @param gmImageLock the value for golden_master_images.gm_image_lock
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setGmImageLock(String gmImageLock) {
        this.gmImageLock = gmImageLock == null ? null : gmImageLock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column golden_master_images.gm_image_creation_date
     *
     * @return the value of golden_master_images.gm_image_creation_date
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Date getGmImageCreationDate() {
        return gmImageCreationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column golden_master_images.gm_image_creation_date
     *
     * @param gmImageCreationDate the value for golden_master_images.gm_image_creation_date
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setGmImageCreationDate(Date gmImageCreationDate) {
        this.gmImageCreationDate = gmImageCreationDate;
    }
}