package com.probridge.vbox.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PreApprovedUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public PreApprovedUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPreapproveUserNameIsNull() {
            addCriterion("preapprove_user_name is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameIsNotNull() {
            addCriterion("preapprove_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameEqualTo(String value) {
            addCriterion("preapprove_user_name =", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameNotEqualTo(String value) {
            addCriterion("preapprove_user_name <>", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameGreaterThan(String value) {
            addCriterion("preapprove_user_name >", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("preapprove_user_name >=", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameLessThan(String value) {
            addCriterion("preapprove_user_name <", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameLessThanOrEqualTo(String value) {
            addCriterion("preapprove_user_name <=", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameLike(String value) {
            addCriterion("preapprove_user_name like", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameNotLike(String value) {
            addCriterion("preapprove_user_name not like", value, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameIn(List<String> values) {
            addCriterion("preapprove_user_name in", values, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameNotIn(List<String> values) {
            addCriterion("preapprove_user_name not in", values, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameBetween(String value1, String value2) {
            addCriterion("preapprove_user_name between", value1, value2, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveUserNameNotBetween(String value1, String value2) {
            addCriterion("preapprove_user_name not between", value1, value2, "preapproveUserName");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionIsNull() {
            addCriterion("preapprove_description is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionIsNotNull() {
            addCriterion("preapprove_description is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionEqualTo(String value) {
            addCriterion("preapprove_description =", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionNotEqualTo(String value) {
            addCriterion("preapprove_description <>", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionGreaterThan(String value) {
            addCriterion("preapprove_description >", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("preapprove_description >=", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionLessThan(String value) {
            addCriterion("preapprove_description <", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionLessThanOrEqualTo(String value) {
            addCriterion("preapprove_description <=", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionLike(String value) {
            addCriterion("preapprove_description like", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionNotLike(String value) {
            addCriterion("preapprove_description not like", value, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionIn(List<String> values) {
            addCriterion("preapprove_description in", values, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionNotIn(List<String> values) {
            addCriterion("preapprove_description not in", values, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionBetween(String value1, String value2) {
            addCriterion("preapprove_description between", value1, value2, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveDescriptionNotBetween(String value1, String value2) {
            addCriterion("preapprove_description not between", value1, value2, "preapproveDescription");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationIsNull() {
            addCriterion("preapprove_expiration is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationIsNotNull() {
            addCriterion("preapprove_expiration is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationEqualTo(Date value) {
            addCriterion("preapprove_expiration =", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationNotEqualTo(Date value) {
            addCriterion("preapprove_expiration <>", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationGreaterThan(Date value) {
            addCriterion("preapprove_expiration >", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationGreaterThanOrEqualTo(Date value) {
            addCriterion("preapprove_expiration >=", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationLessThan(Date value) {
            addCriterion("preapprove_expiration <", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationLessThanOrEqualTo(Date value) {
            addCriterion("preapprove_expiration <=", value, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationIn(List<Date> values) {
            addCriterion("preapprove_expiration in", values, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationNotIn(List<Date> values) {
            addCriterion("preapprove_expiration not in", values, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationBetween(Date value1, Date value2) {
            addCriterion("preapprove_expiration between", value1, value2, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveExpirationNotBetween(Date value1, Date value2) {
            addCriterion("preapprove_expiration not between", value1, value2, "preapproveExpiration");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterIsNull() {
            addCriterion("preapprove_vm_golden_master is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterIsNotNull() {
            addCriterion("preapprove_vm_golden_master is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterEqualTo(String value) {
            addCriterion("preapprove_vm_golden_master =", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterNotEqualTo(String value) {
            addCriterion("preapprove_vm_golden_master <>", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterGreaterThan(String value) {
            addCriterion("preapprove_vm_golden_master >", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterGreaterThanOrEqualTo(String value) {
            addCriterion("preapprove_vm_golden_master >=", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterLessThan(String value) {
            addCriterion("preapprove_vm_golden_master <", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterLessThanOrEqualTo(String value) {
            addCriterion("preapprove_vm_golden_master <=", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterLike(String value) {
            addCriterion("preapprove_vm_golden_master like", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterNotLike(String value) {
            addCriterion("preapprove_vm_golden_master not like", value, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterIn(List<String> values) {
            addCriterion("preapprove_vm_golden_master in", values, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterNotIn(List<String> values) {
            addCriterion("preapprove_vm_golden_master not in", values, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterBetween(String value1, String value2) {
            addCriterion("preapprove_vm_golden_master between", value1, value2, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmGoldenMasterNotBetween(String value1, String value2) {
            addCriterion("preapprove_vm_golden_master not between", value1, value2, "preapproveVmGoldenMaster");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkIsNull() {
            addCriterion("preapprove_vm_network is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkIsNotNull() {
            addCriterion("preapprove_vm_network is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkEqualTo(String value) {
            addCriterion("preapprove_vm_network =", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkNotEqualTo(String value) {
            addCriterion("preapprove_vm_network <>", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkGreaterThan(String value) {
            addCriterion("preapprove_vm_network >", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkGreaterThanOrEqualTo(String value) {
            addCriterion("preapprove_vm_network >=", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkLessThan(String value) {
            addCriterion("preapprove_vm_network <", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkLessThanOrEqualTo(String value) {
            addCriterion("preapprove_vm_network <=", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkLike(String value) {
            addCriterion("preapprove_vm_network like", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkNotLike(String value) {
            addCriterion("preapprove_vm_network not like", value, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkIn(List<String> values) {
            addCriterion("preapprove_vm_network in", values, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkNotIn(List<String> values) {
            addCriterion("preapprove_vm_network not in", values, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkBetween(String value1, String value2) {
            addCriterion("preapprove_vm_network between", value1, value2, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmNetworkNotBetween(String value1, String value2) {
            addCriterion("preapprove_vm_network not between", value1, value2, "preapproveVmNetwork");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresIsNull() {
            addCriterion("preapprove_vm_cores is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresIsNotNull() {
            addCriterion("preapprove_vm_cores is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresEqualTo(Integer value) {
            addCriterion("preapprove_vm_cores =", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresNotEqualTo(Integer value) {
            addCriterion("preapprove_vm_cores <>", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresGreaterThan(Integer value) {
            addCriterion("preapprove_vm_cores >", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresGreaterThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vm_cores >=", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresLessThan(Integer value) {
            addCriterion("preapprove_vm_cores <", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresLessThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vm_cores <=", value, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresIn(List<Integer> values) {
            addCriterion("preapprove_vm_cores in", values, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresNotIn(List<Integer> values) {
            addCriterion("preapprove_vm_cores not in", values, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vm_cores between", value1, value2, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmCoresNotBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vm_cores not between", value1, value2, "preapproveVmCores");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryIsNull() {
            addCriterion("preapprove_vm_memory is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryIsNotNull() {
            addCriterion("preapprove_vm_memory is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryEqualTo(Integer value) {
            addCriterion("preapprove_vm_memory =", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryNotEqualTo(Integer value) {
            addCriterion("preapprove_vm_memory <>", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryGreaterThan(Integer value) {
            addCriterion("preapprove_vm_memory >", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vm_memory >=", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryLessThan(Integer value) {
            addCriterion("preapprove_vm_memory <", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryLessThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vm_memory <=", value, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryIn(List<Integer> values) {
            addCriterion("preapprove_vm_memory in", values, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryNotIn(List<Integer> values) {
            addCriterion("preapprove_vm_memory not in", values, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vm_memory between", value1, value2, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVmMemoryNotBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vm_memory not between", value1, value2, "preapproveVmMemory");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaIsNull() {
            addCriterion("preapprove_vhd_quota is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaIsNotNull() {
            addCriterion("preapprove_vhd_quota is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaEqualTo(Integer value) {
            addCriterion("preapprove_vhd_quota =", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaNotEqualTo(Integer value) {
            addCriterion("preapprove_vhd_quota <>", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaGreaterThan(Integer value) {
            addCriterion("preapprove_vhd_quota >", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vhd_quota >=", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaLessThan(Integer value) {
            addCriterion("preapprove_vhd_quota <", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("preapprove_vhd_quota <=", value, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaIn(List<Integer> values) {
            addCriterion("preapprove_vhd_quota in", values, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaNotIn(List<Integer> values) {
            addCriterion("preapprove_vhd_quota not in", values, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vhd_quota between", value1, value2, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveVhdQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_vhd_quota not between", value1, value2, "preapproveVhdQuota");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdIsNull() {
            addCriterion("preapprove_hypervisor_id is null");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdIsNotNull() {
            addCriterion("preapprove_hypervisor_id is not null");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdEqualTo(Integer value) {
            addCriterion("preapprove_hypervisor_id =", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdNotEqualTo(Integer value) {
            addCriterion("preapprove_hypervisor_id <>", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdGreaterThan(Integer value) {
            addCriterion("preapprove_hypervisor_id >", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("preapprove_hypervisor_id >=", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdLessThan(Integer value) {
            addCriterion("preapprove_hypervisor_id <", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdLessThanOrEqualTo(Integer value) {
            addCriterion("preapprove_hypervisor_id <=", value, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdIn(List<Integer> values) {
            addCriterion("preapprove_hypervisor_id in", values, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdNotIn(List<Integer> values) {
            addCriterion("preapprove_hypervisor_id not in", values, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_hypervisor_id between", value1, value2, "preapproveHypervisorId");
            return (Criteria) this;
        }

        public Criteria andPreapproveHypervisorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("preapprove_hypervisor_id not between", value1, value2, "preapproveHypervisorId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preapprove_user
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}