package com.probridge.vbox.model;

import java.io.Serializable;
import java.util.Date;

public class PreApprovedUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_user_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String preapproveUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String preapproveDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_expiration
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Date preapproveExpiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_vm_golden_master
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String preapproveVmGoldenMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_vm_network
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String preapproveVmNetwork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_vm_cores
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer preapproveVmCores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_vm_memory
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer preapproveVmMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_vhd_quota
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer preapproveVhdQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column preapprove_user.preapprove_hypervisor_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer preapproveHypervisorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table preapprove_user
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_user_name
     *
     * @return the value of preapprove_user.preapprove_user_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getPreapproveUserName() {
        return preapproveUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_user_name
     *
     * @param preapproveUserName the value for preapprove_user.preapprove_user_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveUserName(String preapproveUserName) {
        this.preapproveUserName = preapproveUserName == null ? null : preapproveUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_description
     *
     * @return the value of preapprove_user.preapprove_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getPreapproveDescription() {
        return preapproveDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_description
     *
     * @param preapproveDescription the value for preapprove_user.preapprove_description
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveDescription(String preapproveDescription) {
        this.preapproveDescription = preapproveDescription == null ? null : preapproveDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_expiration
     *
     * @return the value of preapprove_user.preapprove_expiration
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Date getPreapproveExpiration() {
        return preapproveExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_expiration
     *
     * @param preapproveExpiration the value for preapprove_user.preapprove_expiration
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveExpiration(Date preapproveExpiration) {
        this.preapproveExpiration = preapproveExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_vm_golden_master
     *
     * @return the value of preapprove_user.preapprove_vm_golden_master
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getPreapproveVmGoldenMaster() {
        return preapproveVmGoldenMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_vm_golden_master
     *
     * @param preapproveVmGoldenMaster the value for preapprove_user.preapprove_vm_golden_master
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveVmGoldenMaster(String preapproveVmGoldenMaster) {
        this.preapproveVmGoldenMaster = preapproveVmGoldenMaster == null ? null : preapproveVmGoldenMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_vm_network
     *
     * @return the value of preapprove_user.preapprove_vm_network
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getPreapproveVmNetwork() {
        return preapproveVmNetwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_vm_network
     *
     * @param preapproveVmNetwork the value for preapprove_user.preapprove_vm_network
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveVmNetwork(String preapproveVmNetwork) {
        this.preapproveVmNetwork = preapproveVmNetwork == null ? null : preapproveVmNetwork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_vm_cores
     *
     * @return the value of preapprove_user.preapprove_vm_cores
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getPreapproveVmCores() {
        return preapproveVmCores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_vm_cores
     *
     * @param preapproveVmCores the value for preapprove_user.preapprove_vm_cores
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveVmCores(Integer preapproveVmCores) {
        this.preapproveVmCores = preapproveVmCores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_vm_memory
     *
     * @return the value of preapprove_user.preapprove_vm_memory
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getPreapproveVmMemory() {
        return preapproveVmMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_vm_memory
     *
     * @param preapproveVmMemory the value for preapprove_user.preapprove_vm_memory
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveVmMemory(Integer preapproveVmMemory) {
        this.preapproveVmMemory = preapproveVmMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_vhd_quota
     *
     * @return the value of preapprove_user.preapprove_vhd_quota
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getPreapproveVhdQuota() {
        return preapproveVhdQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_vhd_quota
     *
     * @param preapproveVhdQuota the value for preapprove_user.preapprove_vhd_quota
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveVhdQuota(Integer preapproveVhdQuota) {
        this.preapproveVhdQuota = preapproveVhdQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column preapprove_user.preapprove_hypervisor_id
     *
     * @return the value of preapprove_user.preapprove_hypervisor_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getPreapproveHypervisorId() {
        return preapproveHypervisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column preapprove_user.preapprove_hypervisor_id
     *
     * @param preapproveHypervisorId the value for preapprove_user.preapprove_hypervisor_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setPreapproveHypervisorId(Integer preapproveHypervisorId) {
        this.preapproveHypervisorId = preapproveHypervisorId;
    }
}