package com.probridge.vbox.model;

import java.io.Serializable;

public class SysParam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_sysparam.sysparam_key
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String sysparamKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_sysparam.sysparam_value
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String sysparamValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_sysparam
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_sysparam.sysparam_key
     *
     * @return the value of vbox_sysparam.sysparam_key
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getSysparamKey() {
        return sysparamKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_sysparam.sysparam_key
     *
     * @param sysparamKey the value for vbox_sysparam.sysparam_key
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setSysparamKey(String sysparamKey) {
        this.sysparamKey = sysparamKey == null ? null : sysparamKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_sysparam.sysparam_value
     *
     * @return the value of vbox_sysparam.sysparam_value
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getSysparamValue() {
        return sysparamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_sysparam.sysparam_value
     *
     * @param sysparamValue the value for vbox_sysparam.sysparam_value
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setSysparamValue(String sysparamValue) {
        this.sysparamValue = sysparamValue == null ? null : sysparamValue.trim();
    }
}