package com.probridge.vbox.model;

import java.io.Serializable;
import java.util.Date;

public class VboxRequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer vboxRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_owner
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_code
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_justification
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestJustification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_status
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_vmid
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestVmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Date vboxRequestTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_approval_info
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String vboxRequestApprovalInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_request.vbox_request_approval_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Date vboxRequestApprovalTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_id
     *
     * @return the value of vbox_request.vbox_request_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getVboxRequestId() {
        return vboxRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_id
     *
     * @param vboxRequestId the value for vbox_request.vbox_request_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestId(Integer vboxRequestId) {
        this.vboxRequestId = vboxRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_owner
     *
     * @return the value of vbox_request.vbox_request_owner
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestOwner() {
        return vboxRequestOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_owner
     *
     * @param vboxRequestOwner the value for vbox_request.vbox_request_owner
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestOwner(String vboxRequestOwner) {
        this.vboxRequestOwner = vboxRequestOwner == null ? null : vboxRequestOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_code
     *
     * @return the value of vbox_request.vbox_request_code
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestCode() {
        return vboxRequestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_code
     *
     * @param vboxRequestCode the value for vbox_request.vbox_request_code
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestCode(String vboxRequestCode) {
        this.vboxRequestCode = vboxRequestCode == null ? null : vboxRequestCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_justification
     *
     * @return the value of vbox_request.vbox_request_justification
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestJustification() {
        return vboxRequestJustification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_justification
     *
     * @param vboxRequestJustification the value for vbox_request.vbox_request_justification
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestJustification(String vboxRequestJustification) {
        this.vboxRequestJustification = vboxRequestJustification == null ? null : vboxRequestJustification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_status
     *
     * @return the value of vbox_request.vbox_request_status
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestStatus() {
        return vboxRequestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_status
     *
     * @param vboxRequestStatus the value for vbox_request.vbox_request_status
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestStatus(String vboxRequestStatus) {
        this.vboxRequestStatus = vboxRequestStatus == null ? null : vboxRequestStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_vmid
     *
     * @return the value of vbox_request.vbox_request_vmid
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestVmid() {
        return vboxRequestVmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_vmid
     *
     * @param vboxRequestVmid the value for vbox_request.vbox_request_vmid
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestVmid(String vboxRequestVmid) {
        this.vboxRequestVmid = vboxRequestVmid == null ? null : vboxRequestVmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_timestamp
     *
     * @return the value of vbox_request.vbox_request_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Date getVboxRequestTimestamp() {
        return vboxRequestTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_timestamp
     *
     * @param vboxRequestTimestamp the value for vbox_request.vbox_request_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestTimestamp(Date vboxRequestTimestamp) {
        this.vboxRequestTimestamp = vboxRequestTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_approval_info
     *
     * @return the value of vbox_request.vbox_request_approval_info
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getVboxRequestApprovalInfo() {
        return vboxRequestApprovalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_approval_info
     *
     * @param vboxRequestApprovalInfo the value for vbox_request.vbox_request_approval_info
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestApprovalInfo(String vboxRequestApprovalInfo) {
        this.vboxRequestApprovalInfo = vboxRequestApprovalInfo == null ? null : vboxRequestApprovalInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_request.vbox_request_approval_timestamp
     *
     * @return the value of vbox_request.vbox_request_approval_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Date getVboxRequestApprovalTimestamp() {
        return vboxRequestApprovalTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_request.vbox_request_approval_timestamp
     *
     * @param vboxRequestApprovalTimestamp the value for vbox_request.vbox_request_approval_timestamp
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setVboxRequestApprovalTimestamp(Date vboxRequestApprovalTimestamp) {
        this.vboxRequestApprovalTimestamp = vboxRequestApprovalTimestamp;
    }
}