package com.probridge.vbox.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VboxRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public VboxRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVboxRequestIdIsNull() {
            addCriterion("vbox_request_id is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdIsNotNull() {
            addCriterion("vbox_request_id is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdEqualTo(Integer value) {
            addCriterion("vbox_request_id =", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdNotEqualTo(Integer value) {
            addCriterion("vbox_request_id <>", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdGreaterThan(Integer value) {
            addCriterion("vbox_request_id >", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vbox_request_id >=", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdLessThan(Integer value) {
            addCriterion("vbox_request_id <", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdLessThanOrEqualTo(Integer value) {
            addCriterion("vbox_request_id <=", value, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdIn(List<Integer> values) {
            addCriterion("vbox_request_id in", values, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdNotIn(List<Integer> values) {
            addCriterion("vbox_request_id not in", values, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdBetween(Integer value1, Integer value2) {
            addCriterion("vbox_request_id between", value1, value2, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vbox_request_id not between", value1, value2, "vboxRequestId");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerIsNull() {
            addCriterion("vbox_request_owner is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerIsNotNull() {
            addCriterion("vbox_request_owner is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerEqualTo(String value) {
            addCriterion("vbox_request_owner =", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerNotEqualTo(String value) {
            addCriterion("vbox_request_owner <>", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerGreaterThan(String value) {
            addCriterion("vbox_request_owner >", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_owner >=", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerLessThan(String value) {
            addCriterion("vbox_request_owner <", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_owner <=", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerLike(String value) {
            addCriterion("vbox_request_owner like", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerNotLike(String value) {
            addCriterion("vbox_request_owner not like", value, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerIn(List<String> values) {
            addCriterion("vbox_request_owner in", values, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerNotIn(List<String> values) {
            addCriterion("vbox_request_owner not in", values, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerBetween(String value1, String value2) {
            addCriterion("vbox_request_owner between", value1, value2, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestOwnerNotBetween(String value1, String value2) {
            addCriterion("vbox_request_owner not between", value1, value2, "vboxRequestOwner");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeIsNull() {
            addCriterion("vbox_request_code is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeIsNotNull() {
            addCriterion("vbox_request_code is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeEqualTo(String value) {
            addCriterion("vbox_request_code =", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeNotEqualTo(String value) {
            addCriterion("vbox_request_code <>", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeGreaterThan(String value) {
            addCriterion("vbox_request_code >", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_code >=", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeLessThan(String value) {
            addCriterion("vbox_request_code <", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_code <=", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeLike(String value) {
            addCriterion("vbox_request_code like", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeNotLike(String value) {
            addCriterion("vbox_request_code not like", value, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeIn(List<String> values) {
            addCriterion("vbox_request_code in", values, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeNotIn(List<String> values) {
            addCriterion("vbox_request_code not in", values, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeBetween(String value1, String value2) {
            addCriterion("vbox_request_code between", value1, value2, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestCodeNotBetween(String value1, String value2) {
            addCriterion("vbox_request_code not between", value1, value2, "vboxRequestCode");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationIsNull() {
            addCriterion("vbox_request_justification is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationIsNotNull() {
            addCriterion("vbox_request_justification is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationEqualTo(String value) {
            addCriterion("vbox_request_justification =", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationNotEqualTo(String value) {
            addCriterion("vbox_request_justification <>", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationGreaterThan(String value) {
            addCriterion("vbox_request_justification >", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_justification >=", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationLessThan(String value) {
            addCriterion("vbox_request_justification <", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_justification <=", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationLike(String value) {
            addCriterion("vbox_request_justification like", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationNotLike(String value) {
            addCriterion("vbox_request_justification not like", value, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationIn(List<String> values) {
            addCriterion("vbox_request_justification in", values, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationNotIn(List<String> values) {
            addCriterion("vbox_request_justification not in", values, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationBetween(String value1, String value2) {
            addCriterion("vbox_request_justification between", value1, value2, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestJustificationNotBetween(String value1, String value2) {
            addCriterion("vbox_request_justification not between", value1, value2, "vboxRequestJustification");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusIsNull() {
            addCriterion("vbox_request_status is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusIsNotNull() {
            addCriterion("vbox_request_status is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusEqualTo(String value) {
            addCriterion("vbox_request_status =", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusNotEqualTo(String value) {
            addCriterion("vbox_request_status <>", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusGreaterThan(String value) {
            addCriterion("vbox_request_status >", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_status >=", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusLessThan(String value) {
            addCriterion("vbox_request_status <", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_status <=", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusLike(String value) {
            addCriterion("vbox_request_status like", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusNotLike(String value) {
            addCriterion("vbox_request_status not like", value, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusIn(List<String> values) {
            addCriterion("vbox_request_status in", values, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusNotIn(List<String> values) {
            addCriterion("vbox_request_status not in", values, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusBetween(String value1, String value2) {
            addCriterion("vbox_request_status between", value1, value2, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestStatusNotBetween(String value1, String value2) {
            addCriterion("vbox_request_status not between", value1, value2, "vboxRequestStatus");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidIsNull() {
            addCriterion("vbox_request_vmid is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidIsNotNull() {
            addCriterion("vbox_request_vmid is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidEqualTo(String value) {
            addCriterion("vbox_request_vmid =", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidNotEqualTo(String value) {
            addCriterion("vbox_request_vmid <>", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidGreaterThan(String value) {
            addCriterion("vbox_request_vmid >", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_vmid >=", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidLessThan(String value) {
            addCriterion("vbox_request_vmid <", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_vmid <=", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidLike(String value) {
            addCriterion("vbox_request_vmid like", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidNotLike(String value) {
            addCriterion("vbox_request_vmid not like", value, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidIn(List<String> values) {
            addCriterion("vbox_request_vmid in", values, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidNotIn(List<String> values) {
            addCriterion("vbox_request_vmid not in", values, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidBetween(String value1, String value2) {
            addCriterion("vbox_request_vmid between", value1, value2, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestVmidNotBetween(String value1, String value2) {
            addCriterion("vbox_request_vmid not between", value1, value2, "vboxRequestVmid");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampIsNull() {
            addCriterion("vbox_request_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampIsNotNull() {
            addCriterion("vbox_request_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampEqualTo(Date value) {
            addCriterion("vbox_request_timestamp =", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampNotEqualTo(Date value) {
            addCriterion("vbox_request_timestamp <>", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampGreaterThan(Date value) {
            addCriterion("vbox_request_timestamp >", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("vbox_request_timestamp >=", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampLessThan(Date value) {
            addCriterion("vbox_request_timestamp <", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampLessThanOrEqualTo(Date value) {
            addCriterion("vbox_request_timestamp <=", value, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampIn(List<Date> values) {
            addCriterion("vbox_request_timestamp in", values, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampNotIn(List<Date> values) {
            addCriterion("vbox_request_timestamp not in", values, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampBetween(Date value1, Date value2) {
            addCriterion("vbox_request_timestamp between", value1, value2, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestTimestampNotBetween(Date value1, Date value2) {
            addCriterion("vbox_request_timestamp not between", value1, value2, "vboxRequestTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoIsNull() {
            addCriterion("vbox_request_approval_info is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoIsNotNull() {
            addCriterion("vbox_request_approval_info is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoEqualTo(String value) {
            addCriterion("vbox_request_approval_info =", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoNotEqualTo(String value) {
            addCriterion("vbox_request_approval_info <>", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoGreaterThan(String value) {
            addCriterion("vbox_request_approval_info >", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoGreaterThanOrEqualTo(String value) {
            addCriterion("vbox_request_approval_info >=", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoLessThan(String value) {
            addCriterion("vbox_request_approval_info <", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoLessThanOrEqualTo(String value) {
            addCriterion("vbox_request_approval_info <=", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoLike(String value) {
            addCriterion("vbox_request_approval_info like", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoNotLike(String value) {
            addCriterion("vbox_request_approval_info not like", value, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoIn(List<String> values) {
            addCriterion("vbox_request_approval_info in", values, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoNotIn(List<String> values) {
            addCriterion("vbox_request_approval_info not in", values, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoBetween(String value1, String value2) {
            addCriterion("vbox_request_approval_info between", value1, value2, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalInfoNotBetween(String value1, String value2) {
            addCriterion("vbox_request_approval_info not between", value1, value2, "vboxRequestApprovalInfo");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampIsNull() {
            addCriterion("vbox_request_approval_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampIsNotNull() {
            addCriterion("vbox_request_approval_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampEqualTo(Date value) {
            addCriterion("vbox_request_approval_timestamp =", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampNotEqualTo(Date value) {
            addCriterion("vbox_request_approval_timestamp <>", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampGreaterThan(Date value) {
            addCriterion("vbox_request_approval_timestamp >", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("vbox_request_approval_timestamp >=", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampLessThan(Date value) {
            addCriterion("vbox_request_approval_timestamp <", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampLessThanOrEqualTo(Date value) {
            addCriterion("vbox_request_approval_timestamp <=", value, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampIn(List<Date> values) {
            addCriterion("vbox_request_approval_timestamp in", values, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampNotIn(List<Date> values) {
            addCriterion("vbox_request_approval_timestamp not in", values, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampBetween(Date value1, Date value2) {
            addCriterion("vbox_request_approval_timestamp between", value1, value2, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }

        public Criteria andVboxRequestApprovalTimestampNotBetween(Date value1, Date value2) {
            addCriterion("vbox_request_approval_timestamp not between", value1, value2, "vboxRequestApprovalTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_request
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_request
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}