package com.probridge.vbox.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VMExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public VMExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVmIdIsNull() {
            addCriterion("vm_id is null");
            return (Criteria) this;
        }

        public Criteria andVmIdIsNotNull() {
            addCriterion("vm_id is not null");
            return (Criteria) this;
        }

        public Criteria andVmIdEqualTo(String value) {
            addCriterion("vm_id =", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdNotEqualTo(String value) {
            addCriterion("vm_id <>", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdGreaterThan(String value) {
            addCriterion("vm_id >", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdGreaterThanOrEqualTo(String value) {
            addCriterion("vm_id >=", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdLessThan(String value) {
            addCriterion("vm_id <", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdLessThanOrEqualTo(String value) {
            addCriterion("vm_id <=", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdLike(String value) {
            addCriterion("vm_id like", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdNotLike(String value) {
            addCriterion("vm_id not like", value, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdIn(List<String> values) {
            addCriterion("vm_id in", values, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdNotIn(List<String> values) {
            addCriterion("vm_id not in", values, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdBetween(String value1, String value2) {
            addCriterion("vm_id between", value1, value2, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmIdNotBetween(String value1, String value2) {
            addCriterion("vm_id not between", value1, value2, "vmId");
            return (Criteria) this;
        }

        public Criteria andVmTypeIsNull() {
            addCriterion("vm_type is null");
            return (Criteria) this;
        }

        public Criteria andVmTypeIsNotNull() {
            addCriterion("vm_type is not null");
            return (Criteria) this;
        }

        public Criteria andVmTypeEqualTo(String value) {
            addCriterion("vm_type =", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeNotEqualTo(String value) {
            addCriterion("vm_type <>", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeGreaterThan(String value) {
            addCriterion("vm_type >", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("vm_type >=", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeLessThan(String value) {
            addCriterion("vm_type <", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeLessThanOrEqualTo(String value) {
            addCriterion("vm_type <=", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeLike(String value) {
            addCriterion("vm_type like", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeNotLike(String value) {
            addCriterion("vm_type not like", value, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeIn(List<String> values) {
            addCriterion("vm_type in", values, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeNotIn(List<String> values) {
            addCriterion("vm_type not in", values, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeBetween(String value1, String value2) {
            addCriterion("vm_type between", value1, value2, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmTypeNotBetween(String value1, String value2) {
            addCriterion("vm_type not between", value1, value2, "vmType");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeIsNull() {
            addCriterion("vm_course_code is null");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeIsNotNull() {
            addCriterion("vm_course_code is not null");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeEqualTo(String value) {
            addCriterion("vm_course_code =", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeNotEqualTo(String value) {
            addCriterion("vm_course_code <>", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeGreaterThan(String value) {
            addCriterion("vm_course_code >", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vm_course_code >=", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeLessThan(String value) {
            addCriterion("vm_course_code <", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeLessThanOrEqualTo(String value) {
            addCriterion("vm_course_code <=", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeLike(String value) {
            addCriterion("vm_course_code like", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeNotLike(String value) {
            addCriterion("vm_course_code not like", value, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeIn(List<String> values) {
            addCriterion("vm_course_code in", values, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeNotIn(List<String> values) {
            addCriterion("vm_course_code not in", values, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeBetween(String value1, String value2) {
            addCriterion("vm_course_code between", value1, value2, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmCourseCodeNotBetween(String value1, String value2) {
            addCriterion("vm_course_code not between", value1, value2, "vmCourseCode");
            return (Criteria) this;
        }

        public Criteria andVmNameIsNull() {
            addCriterion("vm_name is null");
            return (Criteria) this;
        }

        public Criteria andVmNameIsNotNull() {
            addCriterion("vm_name is not null");
            return (Criteria) this;
        }

        public Criteria andVmNameEqualTo(String value) {
            addCriterion("vm_name =", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameNotEqualTo(String value) {
            addCriterion("vm_name <>", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameGreaterThan(String value) {
            addCriterion("vm_name >", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameGreaterThanOrEqualTo(String value) {
            addCriterion("vm_name >=", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameLessThan(String value) {
            addCriterion("vm_name <", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameLessThanOrEqualTo(String value) {
            addCriterion("vm_name <=", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameLike(String value) {
            addCriterion("vm_name like", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameNotLike(String value) {
            addCriterion("vm_name not like", value, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameIn(List<String> values) {
            addCriterion("vm_name in", values, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameNotIn(List<String> values) {
            addCriterion("vm_name not in", values, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameBetween(String value1, String value2) {
            addCriterion("vm_name between", value1, value2, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmNameNotBetween(String value1, String value2) {
            addCriterion("vm_name not between", value1, value2, "vmName");
            return (Criteria) this;
        }

        public Criteria andVmTitleIsNull() {
            addCriterion("vm_title is null");
            return (Criteria) this;
        }

        public Criteria andVmTitleIsNotNull() {
            addCriterion("vm_title is not null");
            return (Criteria) this;
        }

        public Criteria andVmTitleEqualTo(String value) {
            addCriterion("vm_title =", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleNotEqualTo(String value) {
            addCriterion("vm_title <>", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleGreaterThan(String value) {
            addCriterion("vm_title >", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleGreaterThanOrEqualTo(String value) {
            addCriterion("vm_title >=", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleLessThan(String value) {
            addCriterion("vm_title <", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleLessThanOrEqualTo(String value) {
            addCriterion("vm_title <=", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleLike(String value) {
            addCriterion("vm_title like", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleNotLike(String value) {
            addCriterion("vm_title not like", value, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleIn(List<String> values) {
            addCriterion("vm_title in", values, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleNotIn(List<String> values) {
            addCriterion("vm_title not in", values, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleBetween(String value1, String value2) {
            addCriterion("vm_title between", value1, value2, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmTitleNotBetween(String value1, String value2) {
            addCriterion("vm_title not between", value1, value2, "vmTitle");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionIsNull() {
            addCriterion("vm_description is null");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionIsNotNull() {
            addCriterion("vm_description is not null");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionEqualTo(String value) {
            addCriterion("vm_description =", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionNotEqualTo(String value) {
            addCriterion("vm_description <>", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionGreaterThan(String value) {
            addCriterion("vm_description >", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("vm_description >=", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionLessThan(String value) {
            addCriterion("vm_description <", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionLessThanOrEqualTo(String value) {
            addCriterion("vm_description <=", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionLike(String value) {
            addCriterion("vm_description like", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionNotLike(String value) {
            addCriterion("vm_description not like", value, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionIn(List<String> values) {
            addCriterion("vm_description in", values, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionNotIn(List<String> values) {
            addCriterion("vm_description not in", values, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionBetween(String value1, String value2) {
            addCriterion("vm_description between", value1, value2, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmDescriptionNotBetween(String value1, String value2) {
            addCriterion("vm_description not between", value1, value2, "vmDescription");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseIsNull() {
            addCriterion("vm_preferred_course is null");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseIsNotNull() {
            addCriterion("vm_preferred_course is not null");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseEqualTo(String value) {
            addCriterion("vm_preferred_course =", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseNotEqualTo(String value) {
            addCriterion("vm_preferred_course <>", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseGreaterThan(String value) {
            addCriterion("vm_preferred_course >", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseGreaterThanOrEqualTo(String value) {
            addCriterion("vm_preferred_course >=", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseLessThan(String value) {
            addCriterion("vm_preferred_course <", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseLessThanOrEqualTo(String value) {
            addCriterion("vm_preferred_course <=", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseLike(String value) {
            addCriterion("vm_preferred_course like", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseNotLike(String value) {
            addCriterion("vm_preferred_course not like", value, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseIn(List<String> values) {
            addCriterion("vm_preferred_course in", values, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseNotIn(List<String> values) {
            addCriterion("vm_preferred_course not in", values, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseBetween(String value1, String value2) {
            addCriterion("vm_preferred_course between", value1, value2, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmPreferredCourseNotBetween(String value1, String value2) {
            addCriterion("vm_preferred_course not between", value1, value2, "vmPreferredCourse");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdIsNull() {
            addCriterion("vm_hypervisor_id is null");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdIsNotNull() {
            addCriterion("vm_hypervisor_id is not null");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdEqualTo(Integer value) {
            addCriterion("vm_hypervisor_id =", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdNotEqualTo(Integer value) {
            addCriterion("vm_hypervisor_id <>", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdGreaterThan(Integer value) {
            addCriterion("vm_hypervisor_id >", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_hypervisor_id >=", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdLessThan(Integer value) {
            addCriterion("vm_hypervisor_id <", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdLessThanOrEqualTo(Integer value) {
            addCriterion("vm_hypervisor_id <=", value, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdIn(List<Integer> values) {
            addCriterion("vm_hypervisor_id in", values, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdNotIn(List<Integer> values) {
            addCriterion("vm_hypervisor_id not in", values, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdBetween(Integer value1, Integer value2) {
            addCriterion("vm_hypervisor_id between", value1, value2, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmHypervisorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_hypervisor_id not between", value1, value2, "vmHypervisorId");
            return (Criteria) this;
        }

        public Criteria andVmDisabledIsNull() {
            addCriterion("vm_disabled is null");
            return (Criteria) this;
        }

        public Criteria andVmDisabledIsNotNull() {
            addCriterion("vm_disabled is not null");
            return (Criteria) this;
        }

        public Criteria andVmDisabledEqualTo(String value) {
            addCriterion("vm_disabled =", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledNotEqualTo(String value) {
            addCriterion("vm_disabled <>", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledGreaterThan(String value) {
            addCriterion("vm_disabled >", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledGreaterThanOrEqualTo(String value) {
            addCriterion("vm_disabled >=", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledLessThan(String value) {
            addCriterion("vm_disabled <", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledLessThanOrEqualTo(String value) {
            addCriterion("vm_disabled <=", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledLike(String value) {
            addCriterion("vm_disabled like", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledNotLike(String value) {
            addCriterion("vm_disabled not like", value, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledIn(List<String> values) {
            addCriterion("vm_disabled in", values, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledNotIn(List<String> values) {
            addCriterion("vm_disabled not in", values, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledBetween(String value1, String value2) {
            addCriterion("vm_disabled between", value1, value2, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmDisabledNotBetween(String value1, String value2) {
            addCriterion("vm_disabled not between", value1, value2, "vmDisabled");
            return (Criteria) this;
        }

        public Criteria andVmOwnerIsNull() {
            addCriterion("vm_owner is null");
            return (Criteria) this;
        }

        public Criteria andVmOwnerIsNotNull() {
            addCriterion("vm_owner is not null");
            return (Criteria) this;
        }

        public Criteria andVmOwnerEqualTo(String value) {
            addCriterion("vm_owner =", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerNotEqualTo(String value) {
            addCriterion("vm_owner <>", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerGreaterThan(String value) {
            addCriterion("vm_owner >", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("vm_owner >=", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerLessThan(String value) {
            addCriterion("vm_owner <", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerLessThanOrEqualTo(String value) {
            addCriterion("vm_owner <=", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerLike(String value) {
            addCriterion("vm_owner like", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerNotLike(String value) {
            addCriterion("vm_owner not like", value, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerIn(List<String> values) {
            addCriterion("vm_owner in", values, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerNotIn(List<String> values) {
            addCriterion("vm_owner not in", values, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerBetween(String value1, String value2) {
            addCriterion("vm_owner between", value1, value2, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmOwnerNotBetween(String value1, String value2) {
            addCriterion("vm_owner not between", value1, value2, "vmOwner");
            return (Criteria) this;
        }

        public Criteria andVmCoresIsNull() {
            addCriterion("vm_cores is null");
            return (Criteria) this;
        }

        public Criteria andVmCoresIsNotNull() {
            addCriterion("vm_cores is not null");
            return (Criteria) this;
        }

        public Criteria andVmCoresEqualTo(Integer value) {
            addCriterion("vm_cores =", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresNotEqualTo(Integer value) {
            addCriterion("vm_cores <>", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresGreaterThan(Integer value) {
            addCriterion("vm_cores >", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_cores >=", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresLessThan(Integer value) {
            addCriterion("vm_cores <", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresLessThanOrEqualTo(Integer value) {
            addCriterion("vm_cores <=", value, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresIn(List<Integer> values) {
            addCriterion("vm_cores in", values, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresNotIn(List<Integer> values) {
            addCriterion("vm_cores not in", values, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresBetween(Integer value1, Integer value2) {
            addCriterion("vm_cores between", value1, value2, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmCoresNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_cores not between", value1, value2, "vmCores");
            return (Criteria) this;
        }

        public Criteria andVmMemoryIsNull() {
            addCriterion("vm_memory is null");
            return (Criteria) this;
        }

        public Criteria andVmMemoryIsNotNull() {
            addCriterion("vm_memory is not null");
            return (Criteria) this;
        }

        public Criteria andVmMemoryEqualTo(Integer value) {
            addCriterion("vm_memory =", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryNotEqualTo(Integer value) {
            addCriterion("vm_memory <>", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryGreaterThan(Integer value) {
            addCriterion("vm_memory >", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_memory >=", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryLessThan(Integer value) {
            addCriterion("vm_memory <", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryLessThanOrEqualTo(Integer value) {
            addCriterion("vm_memory <=", value, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryIn(List<Integer> values) {
            addCriterion("vm_memory in", values, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryNotIn(List<Integer> values) {
            addCriterion("vm_memory not in", values, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryBetween(Integer value1, Integer value2) {
            addCriterion("vm_memory between", value1, value2, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmMemoryNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_memory not between", value1, value2, "vmMemory");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageIsNull() {
            addCriterion("vm_vhd_gm_image is null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageIsNotNull() {
            addCriterion("vm_vhd_gm_image is not null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageEqualTo(String value) {
            addCriterion("vm_vhd_gm_image =", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageNotEqualTo(String value) {
            addCriterion("vm_vhd_gm_image <>", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageGreaterThan(String value) {
            addCriterion("vm_vhd_gm_image >", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageGreaterThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_image >=", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageLessThan(String value) {
            addCriterion("vm_vhd_gm_image <", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageLessThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_image <=", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageLike(String value) {
            addCriterion("vm_vhd_gm_image like", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageNotLike(String value) {
            addCriterion("vm_vhd_gm_image not like", value, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageIn(List<String> values) {
            addCriterion("vm_vhd_gm_image in", values, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageNotIn(List<String> values) {
            addCriterion("vm_vhd_gm_image not in", values, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_image between", value1, value2, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmImageNotBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_image not between", value1, value2, "vmVhdGmImage");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeIsNull() {
            addCriterion("vm_vhd_gm_type is null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeIsNotNull() {
            addCriterion("vm_vhd_gm_type is not null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeEqualTo(String value) {
            addCriterion("vm_vhd_gm_type =", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeNotEqualTo(String value) {
            addCriterion("vm_vhd_gm_type <>", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeGreaterThan(String value) {
            addCriterion("vm_vhd_gm_type >", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_type >=", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeLessThan(String value) {
            addCriterion("vm_vhd_gm_type <", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeLessThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_type <=", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeLike(String value) {
            addCriterion("vm_vhd_gm_type like", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeNotLike(String value) {
            addCriterion("vm_vhd_gm_type not like", value, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeIn(List<String> values) {
            addCriterion("vm_vhd_gm_type in", values, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeNotIn(List<String> values) {
            addCriterion("vm_vhd_gm_type not in", values, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_type between", value1, value2, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmTypeNotBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_type not between", value1, value2, "vmVhdGmType");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameIsNull() {
            addCriterion("vm_vhd_gm_filename is null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameIsNotNull() {
            addCriterion("vm_vhd_gm_filename is not null");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameEqualTo(String value) {
            addCriterion("vm_vhd_gm_filename =", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameNotEqualTo(String value) {
            addCriterion("vm_vhd_gm_filename <>", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameGreaterThan(String value) {
            addCriterion("vm_vhd_gm_filename >", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_filename >=", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameLessThan(String value) {
            addCriterion("vm_vhd_gm_filename <", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameLessThanOrEqualTo(String value) {
            addCriterion("vm_vhd_gm_filename <=", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameLike(String value) {
            addCriterion("vm_vhd_gm_filename like", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameNotLike(String value) {
            addCriterion("vm_vhd_gm_filename not like", value, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameIn(List<String> values) {
            addCriterion("vm_vhd_gm_filename in", values, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameNotIn(List<String> values) {
            addCriterion("vm_vhd_gm_filename not in", values, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_filename between", value1, value2, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdGmFilenameNotBetween(String value1, String value2) {
            addCriterion("vm_vhd_gm_filename not between", value1, value2, "vmVhdGmFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameIsNull() {
            addCriterion("vm_vhd_user_filename is null");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameIsNotNull() {
            addCriterion("vm_vhd_user_filename is not null");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameEqualTo(String value) {
            addCriterion("vm_vhd_user_filename =", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameNotEqualTo(String value) {
            addCriterion("vm_vhd_user_filename <>", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameGreaterThan(String value) {
            addCriterion("vm_vhd_user_filename >", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("vm_vhd_user_filename >=", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameLessThan(String value) {
            addCriterion("vm_vhd_user_filename <", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameLessThanOrEqualTo(String value) {
            addCriterion("vm_vhd_user_filename <=", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameLike(String value) {
            addCriterion("vm_vhd_user_filename like", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameNotLike(String value) {
            addCriterion("vm_vhd_user_filename not like", value, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameIn(List<String> values) {
            addCriterion("vm_vhd_user_filename in", values, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameNotIn(List<String> values) {
            addCriterion("vm_vhd_user_filename not in", values, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameBetween(String value1, String value2) {
            addCriterion("vm_vhd_user_filename between", value1, value2, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmVhdUserFilenameNotBetween(String value1, String value2) {
            addCriterion("vm_vhd_user_filename not between", value1, value2, "vmVhdUserFilename");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeIsNull() {
            addCriterion("vm_network_type is null");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeIsNotNull() {
            addCriterion("vm_network_type is not null");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeEqualTo(String value) {
            addCriterion("vm_network_type =", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeNotEqualTo(String value) {
            addCriterion("vm_network_type <>", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeGreaterThan(String value) {
            addCriterion("vm_network_type >", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("vm_network_type >=", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeLessThan(String value) {
            addCriterion("vm_network_type <", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeLessThanOrEqualTo(String value) {
            addCriterion("vm_network_type <=", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeLike(String value) {
            addCriterion("vm_network_type like", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeNotLike(String value) {
            addCriterion("vm_network_type not like", value, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeIn(List<String> values) {
            addCriterion("vm_network_type in", values, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeNotIn(List<String> values) {
            addCriterion("vm_network_type not in", values, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeBetween(String value1, String value2) {
            addCriterion("vm_network_type between", value1, value2, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmNetworkTypeNotBetween(String value1, String value2) {
            addCriterion("vm_network_type not between", value1, value2, "vmNetworkType");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceIsNull() {
            addCriterion("vm_persistance is null");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceIsNotNull() {
            addCriterion("vm_persistance is not null");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceEqualTo(String value) {
            addCriterion("vm_persistance =", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceNotEqualTo(String value) {
            addCriterion("vm_persistance <>", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceGreaterThan(String value) {
            addCriterion("vm_persistance >", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceGreaterThanOrEqualTo(String value) {
            addCriterion("vm_persistance >=", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceLessThan(String value) {
            addCriterion("vm_persistance <", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceLessThanOrEqualTo(String value) {
            addCriterion("vm_persistance <=", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceLike(String value) {
            addCriterion("vm_persistance like", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceNotLike(String value) {
            addCriterion("vm_persistance not like", value, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceIn(List<String> values) {
            addCriterion("vm_persistance in", values, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceNotIn(List<String> values) {
            addCriterion("vm_persistance not in", values, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceBetween(String value1, String value2) {
            addCriterion("vm_persistance between", value1, value2, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmPersistanceNotBetween(String value1, String value2) {
            addCriterion("vm_persistance not between", value1, value2, "vmPersistance");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagIsNull() {
            addCriterion("vm_init_flag is null");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagIsNotNull() {
            addCriterion("vm_init_flag is not null");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagEqualTo(String value) {
            addCriterion("vm_init_flag =", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagNotEqualTo(String value) {
            addCriterion("vm_init_flag <>", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagGreaterThan(String value) {
            addCriterion("vm_init_flag >", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagGreaterThanOrEqualTo(String value) {
            addCriterion("vm_init_flag >=", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagLessThan(String value) {
            addCriterion("vm_init_flag <", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagLessThanOrEqualTo(String value) {
            addCriterion("vm_init_flag <=", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagLike(String value) {
            addCriterion("vm_init_flag like", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagNotLike(String value) {
            addCriterion("vm_init_flag not like", value, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagIn(List<String> values) {
            addCriterion("vm_init_flag in", values, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagNotIn(List<String> values) {
            addCriterion("vm_init_flag not in", values, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagBetween(String value1, String value2) {
            addCriterion("vm_init_flag between", value1, value2, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmInitFlagNotBetween(String value1, String value2) {
            addCriterion("vm_init_flag not between", value1, value2, "vmInitFlag");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatIsNull() {
            addCriterion("vm_heartbeat is null");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatIsNotNull() {
            addCriterion("vm_heartbeat is not null");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatEqualTo(Integer value) {
            addCriterion("vm_heartbeat =", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatNotEqualTo(Integer value) {
            addCriterion("vm_heartbeat <>", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatGreaterThan(Integer value) {
            addCriterion("vm_heartbeat >", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_heartbeat >=", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatLessThan(Integer value) {
            addCriterion("vm_heartbeat <", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatLessThanOrEqualTo(Integer value) {
            addCriterion("vm_heartbeat <=", value, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatIn(List<Integer> values) {
            addCriterion("vm_heartbeat in", values, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatNotIn(List<Integer> values) {
            addCriterion("vm_heartbeat not in", values, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatBetween(Integer value1, Integer value2) {
            addCriterion("vm_heartbeat between", value1, value2, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmHeartbeatNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_heartbeat not between", value1, value2, "vmHeartbeat");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressIsNull() {
            addCriterion("vm_mac_address is null");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressIsNotNull() {
            addCriterion("vm_mac_address is not null");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressEqualTo(String value) {
            addCriterion("vm_mac_address =", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressNotEqualTo(String value) {
            addCriterion("vm_mac_address <>", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressGreaterThan(String value) {
            addCriterion("vm_mac_address >", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressGreaterThanOrEqualTo(String value) {
            addCriterion("vm_mac_address >=", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressLessThan(String value) {
            addCriterion("vm_mac_address <", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressLessThanOrEqualTo(String value) {
            addCriterion("vm_mac_address <=", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressLike(String value) {
            addCriterion("vm_mac_address like", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressNotLike(String value) {
            addCriterion("vm_mac_address not like", value, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressIn(List<String> values) {
            addCriterion("vm_mac_address in", values, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressNotIn(List<String> values) {
            addCriterion("vm_mac_address not in", values, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressBetween(String value1, String value2) {
            addCriterion("vm_mac_address between", value1, value2, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmMacAddressNotBetween(String value1, String value2) {
            addCriterion("vm_mac_address not between", value1, value2, "vmMacAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressIsNull() {
            addCriterion("vm_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressIsNotNull() {
            addCriterion("vm_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressEqualTo(String value) {
            addCriterion("vm_ip_address =", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressNotEqualTo(String value) {
            addCriterion("vm_ip_address <>", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressGreaterThan(String value) {
            addCriterion("vm_ip_address >", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("vm_ip_address >=", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressLessThan(String value) {
            addCriterion("vm_ip_address <", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressLessThanOrEqualTo(String value) {
            addCriterion("vm_ip_address <=", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressLike(String value) {
            addCriterion("vm_ip_address like", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressNotLike(String value) {
            addCriterion("vm_ip_address not like", value, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressIn(List<String> values) {
            addCriterion("vm_ip_address in", values, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressNotIn(List<String> values) {
            addCriterion("vm_ip_address not in", values, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressBetween(String value1, String value2) {
            addCriterion("vm_ip_address between", value1, value2, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmIpAddressNotBetween(String value1, String value2) {
            addCriterion("vm_ip_address not between", value1, value2, "vmIpAddress");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampIsNull() {
            addCriterion("vm_creation_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampIsNotNull() {
            addCriterion("vm_creation_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampEqualTo(Date value) {
            addCriterion("vm_creation_timestamp =", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampNotEqualTo(Date value) {
            addCriterion("vm_creation_timestamp <>", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampGreaterThan(Date value) {
            addCriterion("vm_creation_timestamp >", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("vm_creation_timestamp >=", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampLessThan(Date value) {
            addCriterion("vm_creation_timestamp <", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampLessThanOrEqualTo(Date value) {
            addCriterion("vm_creation_timestamp <=", value, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampIn(List<Date> values) {
            addCriterion("vm_creation_timestamp in", values, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampNotIn(List<Date> values) {
            addCriterion("vm_creation_timestamp not in", values, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampBetween(Date value1, Date value2) {
            addCriterion("vm_creation_timestamp between", value1, value2, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCreationTimestampNotBetween(Date value1, Date value2) {
            addCriterion("vm_creation_timestamp not between", value1, value2, "vmCreationTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmStatusIsNull() {
            addCriterion("vm_status is null");
            return (Criteria) this;
        }

        public Criteria andVmStatusIsNotNull() {
            addCriterion("vm_status is not null");
            return (Criteria) this;
        }

        public Criteria andVmStatusEqualTo(Integer value) {
            addCriterion("vm_status =", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusNotEqualTo(Integer value) {
            addCriterion("vm_status <>", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusGreaterThan(Integer value) {
            addCriterion("vm_status >", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_status >=", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusLessThan(Integer value) {
            addCriterion("vm_status <", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusLessThanOrEqualTo(Integer value) {
            addCriterion("vm_status <=", value, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusIn(List<Integer> values) {
            addCriterion("vm_status in", values, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusNotIn(List<Integer> values) {
            addCriterion("vm_status not in", values, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusBetween(Integer value1, Integer value2) {
            addCriterion("vm_status between", value1, value2, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_status not between", value1, value2, "vmStatus");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordIsNull() {
            addCriterion("vm_guest_password is null");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordIsNotNull() {
            addCriterion("vm_guest_password is not null");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordEqualTo(String value) {
            addCriterion("vm_guest_password =", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordNotEqualTo(String value) {
            addCriterion("vm_guest_password <>", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordGreaterThan(String value) {
            addCriterion("vm_guest_password >", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("vm_guest_password >=", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordLessThan(String value) {
            addCriterion("vm_guest_password <", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordLessThanOrEqualTo(String value) {
            addCriterion("vm_guest_password <=", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordLike(String value) {
            addCriterion("vm_guest_password like", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordNotLike(String value) {
            addCriterion("vm_guest_password not like", value, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordIn(List<String> values) {
            addCriterion("vm_guest_password in", values, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordNotIn(List<String> values) {
            addCriterion("vm_guest_password not in", values, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordBetween(String value1, String value2) {
            addCriterion("vm_guest_password between", value1, value2, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmGuestPasswordNotBetween(String value1, String value2) {
            addCriterion("vm_guest_password not between", value1, value2, "vmGuestPassword");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampIsNull() {
            addCriterion("vm_last_update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampIsNotNull() {
            addCriterion("vm_last_update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampEqualTo(Date value) {
            addCriterion("vm_last_update_timestamp =", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampNotEqualTo(Date value) {
            addCriterion("vm_last_update_timestamp <>", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampGreaterThan(Date value) {
            addCriterion("vm_last_update_timestamp >", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("vm_last_update_timestamp >=", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampLessThan(Date value) {
            addCriterion("vm_last_update_timestamp <", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("vm_last_update_timestamp <=", value, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampIn(List<Date> values) {
            addCriterion("vm_last_update_timestamp in", values, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampNotIn(List<Date> values) {
            addCriterion("vm_last_update_timestamp not in", values, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("vm_last_update_timestamp between", value1, value2, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmLastUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("vm_last_update_timestamp not between", value1, value2, "vmLastUpdateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table virtual_machines
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table virtual_machines
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}