package com.probridge.vbox.model;

import java.util.ArrayList;
import java.util.List;

public class WordOfTheDayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public WordOfTheDayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWofdIdIsNull() {
            addCriterion("wofd_id is null");
            return (Criteria) this;
        }

        public Criteria andWofdIdIsNotNull() {
            addCriterion("wofd_id is not null");
            return (Criteria) this;
        }

        public Criteria andWofdIdEqualTo(Integer value) {
            addCriterion("wofd_id =", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdNotEqualTo(Integer value) {
            addCriterion("wofd_id <>", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdGreaterThan(Integer value) {
            addCriterion("wofd_id >", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wofd_id >=", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdLessThan(Integer value) {
            addCriterion("wofd_id <", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdLessThanOrEqualTo(Integer value) {
            addCriterion("wofd_id <=", value, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdIn(List<Integer> values) {
            addCriterion("wofd_id in", values, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdNotIn(List<Integer> values) {
            addCriterion("wofd_id not in", values, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdBetween(Integer value1, Integer value2) {
            addCriterion("wofd_id between", value1, value2, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wofd_id not between", value1, value2, "wofdId");
            return (Criteria) this;
        }

        public Criteria andWofdChineseIsNull() {
            addCriterion("wofd_chinese is null");
            return (Criteria) this;
        }

        public Criteria andWofdChineseIsNotNull() {
            addCriterion("wofd_chinese is not null");
            return (Criteria) this;
        }

        public Criteria andWofdChineseEqualTo(String value) {
            addCriterion("wofd_chinese =", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNotEqualTo(String value) {
            addCriterion("wofd_chinese <>", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseGreaterThan(String value) {
            addCriterion("wofd_chinese >", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseGreaterThanOrEqualTo(String value) {
            addCriterion("wofd_chinese >=", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseLessThan(String value) {
            addCriterion("wofd_chinese <", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseLessThanOrEqualTo(String value) {
            addCriterion("wofd_chinese <=", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseLike(String value) {
            addCriterion("wofd_chinese like", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNotLike(String value) {
            addCriterion("wofd_chinese not like", value, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseIn(List<String> values) {
            addCriterion("wofd_chinese in", values, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNotIn(List<String> values) {
            addCriterion("wofd_chinese not in", values, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseBetween(String value1, String value2) {
            addCriterion("wofd_chinese between", value1, value2, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNotBetween(String value1, String value2) {
            addCriterion("wofd_chinese not between", value1, value2, "wofdChinese");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameIsNull() {
            addCriterion("wofd_chinese_name is null");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameIsNotNull() {
            addCriterion("wofd_chinese_name is not null");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameEqualTo(String value) {
            addCriterion("wofd_chinese_name =", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameNotEqualTo(String value) {
            addCriterion("wofd_chinese_name <>", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameGreaterThan(String value) {
            addCriterion("wofd_chinese_name >", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameGreaterThanOrEqualTo(String value) {
            addCriterion("wofd_chinese_name >=", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameLessThan(String value) {
            addCriterion("wofd_chinese_name <", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameLessThanOrEqualTo(String value) {
            addCriterion("wofd_chinese_name <=", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameLike(String value) {
            addCriterion("wofd_chinese_name like", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameNotLike(String value) {
            addCriterion("wofd_chinese_name not like", value, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameIn(List<String> values) {
            addCriterion("wofd_chinese_name in", values, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameNotIn(List<String> values) {
            addCriterion("wofd_chinese_name not in", values, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameBetween(String value1, String value2) {
            addCriterion("wofd_chinese_name between", value1, value2, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdChineseNameNotBetween(String value1, String value2) {
            addCriterion("wofd_chinese_name not between", value1, value2, "wofdChineseName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishIsNull() {
            addCriterion("wofd_english is null");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishIsNotNull() {
            addCriterion("wofd_english is not null");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishEqualTo(String value) {
            addCriterion("wofd_english =", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNotEqualTo(String value) {
            addCriterion("wofd_english <>", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishGreaterThan(String value) {
            addCriterion("wofd_english >", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishGreaterThanOrEqualTo(String value) {
            addCriterion("wofd_english >=", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishLessThan(String value) {
            addCriterion("wofd_english <", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishLessThanOrEqualTo(String value) {
            addCriterion("wofd_english <=", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishLike(String value) {
            addCriterion("wofd_english like", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNotLike(String value) {
            addCriterion("wofd_english not like", value, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishIn(List<String> values) {
            addCriterion("wofd_english in", values, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNotIn(List<String> values) {
            addCriterion("wofd_english not in", values, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishBetween(String value1, String value2) {
            addCriterion("wofd_english between", value1, value2, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNotBetween(String value1, String value2) {
            addCriterion("wofd_english not between", value1, value2, "wofdEnglish");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameIsNull() {
            addCriterion("wofd_english_name is null");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameIsNotNull() {
            addCriterion("wofd_english_name is not null");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameEqualTo(String value) {
            addCriterion("wofd_english_name =", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameNotEqualTo(String value) {
            addCriterion("wofd_english_name <>", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameGreaterThan(String value) {
            addCriterion("wofd_english_name >", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("wofd_english_name >=", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameLessThan(String value) {
            addCriterion("wofd_english_name <", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("wofd_english_name <=", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameLike(String value) {
            addCriterion("wofd_english_name like", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameNotLike(String value) {
            addCriterion("wofd_english_name not like", value, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameIn(List<String> values) {
            addCriterion("wofd_english_name in", values, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameNotIn(List<String> values) {
            addCriterion("wofd_english_name not in", values, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameBetween(String value1, String value2) {
            addCriterion("wofd_english_name between", value1, value2, "wofdEnglishName");
            return (Criteria) this;
        }

        public Criteria andWofdEnglishNameNotBetween(String value1, String value2) {
            addCriterion("wofd_english_name not between", value1, value2, "wofdEnglishName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_wofd
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}