package com.probridge.vbox.model;

import java.io.Serializable;

public class WordOfTheDay implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_wofd.wofd_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private Integer wofdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_wofd.wofd_chinese
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String wofdChinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_wofd.wofd_chinese_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String wofdChineseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_wofd.wofd_english
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String wofdEnglish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vbox_wofd.wofd_english_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private String wofdEnglishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vbox_wofd
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_wofd.wofd_id
     *
     * @return the value of vbox_wofd.wofd_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public Integer getWofdId() {
        return wofdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_wofd.wofd_id
     *
     * @param wofdId the value for vbox_wofd.wofd_id
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setWofdId(Integer wofdId) {
        this.wofdId = wofdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_wofd.wofd_chinese
     *
     * @return the value of vbox_wofd.wofd_chinese
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getWofdChinese() {
        return wofdChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_wofd.wofd_chinese
     *
     * @param wofdChinese the value for vbox_wofd.wofd_chinese
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setWofdChinese(String wofdChinese) {
        this.wofdChinese = wofdChinese == null ? null : wofdChinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_wofd.wofd_chinese_name
     *
     * @return the value of vbox_wofd.wofd_chinese_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getWofdChineseName() {
        return wofdChineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_wofd.wofd_chinese_name
     *
     * @param wofdChineseName the value for vbox_wofd.wofd_chinese_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setWofdChineseName(String wofdChineseName) {
        this.wofdChineseName = wofdChineseName == null ? null : wofdChineseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_wofd.wofd_english
     *
     * @return the value of vbox_wofd.wofd_english
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getWofdEnglish() {
        return wofdEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_wofd.wofd_english
     *
     * @param wofdEnglish the value for vbox_wofd.wofd_english
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setWofdEnglish(String wofdEnglish) {
        this.wofdEnglish = wofdEnglish == null ? null : wofdEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vbox_wofd.wofd_english_name
     *
     * @return the value of vbox_wofd.wofd_english_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public String getWofdEnglishName() {
        return wofdEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vbox_wofd.wofd_english_name
     *
     * @param wofdEnglishName the value for vbox_wofd.wofd_english_name
     *
     * @mbggenerated Sun Jan 19 09:59:57 CST 2014
     */
    public void setWofdEnglishName(String wofdEnglishName) {
        this.wofdEnglishName = wofdEnglishName == null ? null : wofdEnglishName.trim();
    }
}